package atividadeum;
// Generated 09/11/2019 17:26:02 by Hibernate Tools 4.3.1



/**
 * Nota generated by hbm2java
 */
public class Nota  implements java.io.Serializable {


     private Integer notCodigo;
     private Aluno aluno;
     private float notNota;

    public Nota() {
    }

    public Nota(Aluno aluno, float notNota) {
       this.aluno = aluno;
       this.notNota = notNota;
    }
   
    public Integer getNotCodigo() {
        return this.notCodigo;
    }
    
    public void setNotCodigo(Integer notCodigo) {
        this.notCodigo = notCodigo;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public float getNotNota() {
        return this.notNota;
    }
    
    public void setNotNota(float notNota) {
        this.notNota = notNota;
    }




}


